CREATE TABLE PESSOA (
  CPF VARCHAR(15) NOT NULL,
  SEXO VARCHAR(10),
  CEP INT NOT NULL,
  BAIRRO VARCHAR(60),
  CIDADE VARCHAR(60),
  RUA VARCHAR(60),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(80),

  CONSTRAINT pk_pessoa PRIMARY KEY(CPF),
);

CREATE TABLE FONE_PESSOA (
  CPF VARCHAR(15) NOT NULL,
  FONE VARCHAR(10) NOT NULL,

  CONSTRAINT fk_fone FOREIGN KEY CPF REFERENCES PESSOA(CPF)
);

CREATE TABLE EMAIL (
  CPF VARCHAR(15) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,

  CONSTRAINT fk_email FOREIGN KEY CPF REFERENCES PESSOA(CPF)
);

CREATE TABLE CLINICA (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  CAPACIDADE INT NOT NULL,
  CEP INT NOT NULL,
  BAIRRO VARCHAR(60),
  CIDADE VARCHAR(60),
  RUA VARCHAR(60),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(80),
);

CREATE TABLE FONE_CLINICA (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  FONE VARCHAR(10) NOT NULL,

  CONSTRAINT fk_fone_clinica FOREIGN KEY ID REFERENCES CLINICA(ID)
);

CREATE TABLE FUNCIONARIO (
  CPF VARCHAR(15) NOT NULL,
  MATRICULA INT NOT NULL,
  ID_CLINICA INT NOT NULL,
  
  CONSTRAINT fk_funcionario FOREIGN KEY CPF REFERENCES PESSOA(CPF)
);

CREATE TABLE PACIENTE (
  CPF VARCHAR(15) NOT NULL,
  IDENTIFICADOR,

  CONSTRAINT fk_paciente FOREIGN KEY CPF REFERENCES PESSOA(CPF)
);

CREATE TABLE RECEPCIONISTA (
  CPF VARCHAR(15) NOT NULL,
  IDENTIFICADOR,

  CONSTRAINT fk_recepcionista FOREIGN KEY CPF REFERENCES FUNCIONARIO(CPF)
);

CREATE TABLE MEDICO (
  CPF VARCHAR(15) NOT NULL,
  CHEFIA VARCHAR(15),
  CRM INT NOT NULL,

  CONSTRAINT fk_medico FOREIGN KEY CPF REFERENCES FUNCIONARIO(CPF),

  CONSTRAINT fk_chefia FOREIGN KEY CHEFIA REFERENCES MEDICO(CPF)
);

CREATE TABLE EXAME (
  CPF VARCHAR(15) NOT NULL,
  COD INT PRIMARY KEY AUTO_INCREMENT,

  CONSTRAINT fk_exame FOREIGN KEY CPF REFERENCES PACIENTE(CPF)
);

CREATE TABLE MEDICAMENTO (
  CPF VARCHAR(15) NOT NULL,
  COD INT PRIMARY KEY AUTO_INCREMENT,
  MEDICAMENTO VARCHAR(80) NOT NULL,

  CONSTRAINT fk_cpf_medicamento FOREIGN KEY CPF REFERENCES EXAME(CPF),
  CONSTRAINT fk_cod_medicamento FOREIGN KEY COD REFERENCES EXAME(COD)
);

CREATE TABLE AGENDAMENTO (
  CPF_PACIENTE VARCHAR(15) NOT NULL,
  CPF_RECEPCIONISTA VARCHAR(15) NOT NULL,
  CPF_MEDICO VARCHAR(15) NOT NULL,
  FORMULARIO VARCHAR(256) NOT NULL,

  CONSTRAINT fk_cpf_paciente FOREIGN KEY CPF_PACIENTE REFERENCES PACIENTE(CPF),

  CONSTRAINT fk_cpf_recepcionista FOREIGN KEY CPF_RECEPCIONISTA REFERENCES RECEPCIONISTA(CPF),

  CONSTRAINT fk_cpf_medico FOREIGN KEY CPF_MEDICO REFERENCES MEDICO(CPF)
);

CREATE TABLE CONSULTA (
  CREATED_AT TIMESTAMP DEFAULT,
  CPF_PACIENTE VARCHAR(15) NOT NULL,
  CPF_RECEPCIONISTA VARCHAR(15) NOT NULL,
  CPF_MEDICO VARCHAR(15) NOT NULL,
  FORMULARIO_AGENDAMENTO VARCHAR(256) NOT NULL,

  CONSTRAINT fk_consulta_pac FOREIGN KEY CPF_PACIENTE REFERENCES AGENDAMENTO(CPF_PACIENTE),

  CONSTRAINT fk_consulta_recionista FOREIGN KEY CPF_RECEPCIONISTA REFERENCES AGENDAMENTO(CPF_RECEPCIONISTA),

  CONSTRAINT fk_consulta_med FOREIGN KEY CPF_MEDICO REFERENCES AGENDAMENTO(CPF_MEDICO)
)