-- 1.
CREATE TABLE PESSOA (
  NOME VARCHAR(80) NOT NULL,
  CPF VARCHAR(15) NOT NULL,
  NASCIMENTO VARCHAR(10),
  SEXO VARCHAR(10),
  CEP VARCHAR(10) NOT NULL,
  BAIRRO VARCHAR(60),
  CIDADE VARCHAR(60),
  RUA VARCHAR(60),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(80),

  CONSTRAINT pk_pessoa PRIMARY KEY(CPF)
);

-- 2.
CREATE TABLE FONE_PESSOA (
  CPF VARCHAR(15) NOT NULL,
  FONE VARCHAR(10) NOT NULL,

  CONSTRAINT pk_fone PRIMARY KEY (FONE, CPF),
  CONSTRAINT fk_fone FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
);

-- 3.
CREATE TABLE EMAIL_PESSOA (
  CPF VARCHAR(15) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,

  CONSTRAINT pk_email PRIMARY KEY (CPF, EMAIL),
  CONSTRAINT fk_email FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
);

-- 4.
CREATE TABLE CLINICA (
  ID_CLINICA INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  RAZAO_SOCIAL VARCHAR (100),
  CAPACIDADE INT NOT NULL,
  CEP VARCHAR(10) NOT NULL,
  BAIRRO VARCHAR(60),
  CIDADE VARCHAR(60),
  RUA VARCHAR(60),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(80),

  CONSTRAINT pk_clinica PRIMARY KEY (ID_CLINICA)
);

-- 5.
CREATE TABLE FONE_CLINICA (
  ID_CLINICA INT NOT NULL,
  FONE VARCHAR(10) NOT NULL,

  CONSTRAINT pk_fone_clinica PRIMARY KEY (ID_CLINICA, FONE),
  CONSTRAINT fk_fone_clinica FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA)
);

-- 6.
CREATE TABLE FUNCIONARIO (
  CPF VARCHAR(15) NOT NULL,
  MATRICULA INT NOT NULL,
  ID_CLINICA INT NOT NULL,

  CONSTRAINT pk_funcionario PRIMARY KEY (CPF),
  CONSTRAINT fk_funcionario FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
  CONSTRAINT fk_func_clinica FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA)
);

-- 7.
CREATE TABLE PACIENTE (
  CPF VARCHAR(15) NOT NULL,
  IDENTIFICADOR INT,

  CONSTRAINT pk_paciente PRIMARY KEY (CPF),
  CONSTRAINT fk_paciente FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
);

-- 8.
CREATE TABLE SETOR (
  DESCRICAO VARCHAR(15) NOT NULL,

  CONSTRAINT pk_setor PRIMARY KEY (DESCRICAO)
);

-- 9.
CREATE TABLE RECEPCIONISTA (
  CPF VARCHAR(15) NOT NULL,
  DESCRICAO VARCHAR(15) UNIQUE NOT NULL,

  CONSTRAINT pk_recepcionista PRIMARY KEY (CPF),
  CONSTRAINT fk_recepcionista FOREIGN KEY (CPF) REFERENCES FUNCIONARIO(CPF)
);

-- 10.
CREATE TABLE MEDICOS (
  CPF VARCHAR(15) NOT NULL,
  SUPERVISOR VARCHAR(15),
  CRM INT NOT NULL,

  CONSTRAINT pk_medico PRIMARY KEY (CPF),
  CONSTRAINT fk_medico FOREIGN KEY (CPF) REFERENCES FUNCIONARIO(CPF),
  CONSTRAINT fk_chefia FOREIGN KEY (SUPERVISOR) REFERENCES MEDICOS(CPF)
);

-- 18.
CREATE TABLE FORMULARIO (
  CODIGO INT NOT NULL,
  DATA_FORMULARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  TIPO VARCHAR(50),

  CONSTRAINT pk_formulario PRIMARY KEY (CODIGO)
);

-- 11.
CREATE TABLE AGENDAMENTO (
  CODIGO INT NOT NULL,
  CPF_PACIENTE VARCHAR(15) NOT NULL,
  CPF_RECEPCIONISTA VARCHAR(15) NOT NULL,
  CPF_MEDICO VARCHAR(15) NOT NULL,
  COD_FORMULARIO INT NOT NULL,

  CONSTRAINT pk_agendamento PRIMARY KEY (CODIGO),
  CONSTRAINT fk_cpf_paciente FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF),
  CONSTRAINT fk_cpf_recepcionista FOREIGN KEY (CPF_RECEPCIONISTA) REFERENCES RECEPCIONISTA(CPF),
  CONSTRAINT fk_cpf_medico FOREIGN KEY (CPF_MEDICO) REFERENCES MEDICOS(CPF),
  CONSTRAINT fk_formulario FOREIGN KEY (COD_FORMULARIO) REFERENCES FORMULARIO(CODIGO)
);

-- 12.
CREATE TABLE EMPRESA_TERCEIRIZADA (
  CNPJ VARCHAR(20) NOT NULL,
  RAZAO_SOCIAL VARCHAR (100),
  FUNCAO VARCHAR (40),
  CONTATO VARCHAR (10),

  CONSTRAINT pk_empresa PRIMARY KEY (CNPJ)
);

-- 13.
CREATE TABLE CONTRATO (
  COD INT NOT NULL,
  DATA VARCHAR (15),
  VALOR VARCHAR (15),

  CONSTRAINT pk_contrato PRIMARY KEY (COD)
);

-- 14.
CREATE TABLE SERVICO (
  ID_SERVICO INT NOT NULL,
  COD INT NOT NULL,
  CNPJ VARCHAR(20) NOT NULL,

  CONSTRAINT pk_servico PRIMARY KEY (ID_SERVICO, COD, CNPJ),
  CONSTRAINT fk_id_servico FOREIGN KEY (ID_SERVICO) REFERENCES CLINICA(ID_CLINICA),
  CONSTRAINT fk_cod_servico FOREIGN KEY (COD) REFERENCES CONTRATO(COD),
  CONSTRAINT fk_cnpj_servico FOREIGN KEY (CNPJ) REFERENCES EMPRESA_TERCEIRIZADA(CNPJ)
);

-- 17.
CREATE TABLE PAGA_FUNCIONARIO (
  ID_PAGA INT NOT NULL,
  CPF VARCHAR (15) NOT NULL,
  DATA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VALOR VARCHAR(15),

  CONSTRAINT pk_paga_funcionario PRIMARY KEY (ID_PAGA, CPF),
  CONSTRAINT fk_id_paga_funcionario FOREIGN KEY (ID_PAGA) REFERENCES CLINICA(ID_CLINICA),
  CONSTRAINT fk_cpf_paga_funcionario FOREIGN KEY (CPF) REFERENCES FUNCIONARIO(CPF)
);

-- 15.
CREATE TABLE BENEFICIO (
  COD INT NOT NULL,
  ID_BENEFICIO INT NOT NULL,
  CPF VARCHAR(15) NOT NULL,

  CONSTRAINT pk_beneficio PRIMARY KEY (COD),
  CONSTRAINT fk_beneficio FOREIGN KEY (ID_BENEFICIO, CPF) REFERENCES PAGA_FUNCIONARIO(ID_PAGA, CPF)
);

-- 16.
CREATE TABLE TIPO_BENEFICIO (
  COD INT NOT NULL,
  TIPO VARCHAR(40) NOT NULL,

  CONSTRAINT pk_tipo_beneficio PRIMARY KEY (COD, TIPO),
  CONSTRAINT fk_cod_tipo FOREIGN KEY (COD) REFERENCES BENEFICIO(COD)
);
