-- MOSTRANDO NOME DA CLINICA QUE POSSUEM MAIS DE 10 FUNCIONARIOS (COM INNER JOIN)
select c.razao_social, count(*) qtd_func from funcionario f
inner join clinica c on c.id = f.id_clinica
group by c.razao_social
having count(*) > 10

-- MOSTRANDO ID DAS CLINICAS QUE TEM MAIS FUNCIONARIOS QUE A MÉDIA 
SELECT ID_CLINICA, COUNT(*) 
FROM FUNCIONARIO 
GROUP BY ID_CLINICA
HAVING COUNT(*) > (SELECT AVG(QTD)
                    FROM (SELECT ID_CLINICA, COUNT(*) AS QTD
                            FROM FUNCIONARIO GROUP BY ID_CLINICA));
                            
--MOSTRANDO NOME DAS CLINICAS QUE TEM MAIS FUNCIONARIO QUE A MÉDIA
SELECT C.RAZAO_SOCIAL, COUNT(*) 
FROM FUNCIONARIO F
INNER JOIN CLINICA C 
ON (F.ID_CLINICA = C.ID)
GROUP BY C.RAZAO_SOCIAL
HAVING COUNT(*) > (SELECT AVG(QTD)
                    FROM (SELECT ID_CLINICA, COUNT(*) AS QTD
                            FROM FUNCIONARIO GROUP BY ID_CLINICA));
                            
--MOSTRANDO FUNCIONARIOS (NOME, CPF) QUE NAO RECEBEM SALARIO
SELECT NOME, CPF FROM FUNCIONARIO 
WHERE CPF NOT IN (SELECT CPF 
                        FROM PAGA_FUNCIONARIO);

--NOME DOS MÉDICOS QUE RECEBE MAIS DE 5 MIL (COM INNER JOIN)
SELECT F.NOME, M.CRM 
FROM FUNCIONARIO F 
INNER JOIN MEDICOS M 
ON (M.CPF = F.CPF)
INNER JOIN PAGA_FUNCIONARIO P
ON (P.CPF = F.CPF)
WHERE P.VALOR > 5000;
                        
--NOME DOS MÉDICOS QUE RECEBE MAIS DE 5 MIL (COM SUB-CONSULTA)
SELECT F.NOME, M.CRM 
FROM FUNCIONARIO F 
INNER JOIN MEDICOS M 
ON (M.CPF = F.CPF)
WHERE M.CPF IN (SELECT CPF 
                FROM PAGA_FUNCIONARIO
                WHERE VALOR > 5000);    
