-- Lembrar de criar script para insert de 30 recepcionistas!

INSERT INTO MEDICOS (CRM)
VALUES ('21916181');
INSERT INTO MEDICOS (CRM)
VALUES ('68643613');
INSERT INTO MEDICOS (CRM)
VALUES ('21884167');
INSERT INTO MEDICOS (CRM)
VALUES ('33522563');
INSERT INTO MEDICOS (CRM)
VALUES ('89242658');
INSERT INTO MEDICOS (CRM)
VALUES ('82091316');
INSERT INTO MEDICOS (CRM)
VALUES ('85789428');
INSERT INTO MEDICOS (CRM)
VALUES ('36792536');
INSERT INTO MEDICOS (CRM)
VALUES ('45833256');
INSERT INTO MEDICOS (CRM)
VALUES ('94115234');
INSERT INTO MEDICOS (CRM)
VALUES ('65883276');
INSERT INTO MEDICOS (CRM)
VALUES ('50578221');
INSERT INTO MEDICOS (CRM)
VALUES ('16061529');
INSERT INTO MEDICOS (CRM)
VALUES ('58231204');
INSERT INTO MEDICOS (CRM)
VALUES ('58929284');
INSERT INTO MEDICOS (CRM)
VALUES ('81688518');
INSERT INTO MEDICOS (CRM)
VALUES ('60681948');
INSERT INTO MEDICOS (CRM)
VALUES ('67256100');
INSERT INTO MEDICOS (CRM)
VALUES ('65508187');
INSERT INTO MEDICOS (CRM)
VALUES ('62269324');
INSERT INTO MEDICOS (CRM)
VALUES ('34411368');
INSERT INTO MEDICOS (CRM)
VALUES ('96867813');
INSERT INTO MEDICOS (CRM)
VALUES ('27551360');
INSERT INTO MEDICOS (CRM)
VALUES ('20013386');
INSERT INTO MEDICOS (CRM)
VALUES ('66043713');
INSERT INTO MEDICOS (CRM)
VALUES ('53078469');
INSERT INTO MEDICOS (CRM)
VALUES ('68007382');
INSERT INTO MEDICOS (CRM)
VALUES ('82127270');
INSERT INTO MEDICOS (CRM)
VALUES ('37123677');
INSERT INTO MEDICOS (CRM)
VALUES ('95454808');
INSERT INTO MEDICOS (CRM)
VALUES ('67554325');
INSERT INTO MEDICOS (CRM)
VALUES ('81577369');
INSERT INTO MEDICOS (CRM)
VALUES ('44315581');
INSERT INTO MEDICOS (CRM)
VALUES ('50306753');
INSERT INTO MEDICOS (CRM)
VALUES ('83112329');
INSERT INTO MEDICOS (CRM)
VALUES ('65040712');
INSERT INTO MEDICOS (CRM)
VALUES ('92410313');
INSERT INTO MEDICOS (CRM)
VALUES ('65437871');
INSERT INTO MEDICOS (CRM)
VALUES ('82785521');
INSERT INTO MEDICOS (CRM)
VALUES ('15681356');
INSERT INTO MEDICOS (CRM)
VALUES ('63278904');
INSERT INTO MEDICOS (CRM)
VALUES ('33354162');
INSERT INTO MEDICOS (CRM)
VALUES ('67554376');
INSERT INTO MEDICOS (CRM)
VALUES ('93585728');
INSERT INTO MEDICOS (CRM)
VALUES ('99214286');
INSERT INTO MEDICOS (CRM)
VALUES ('65187288');
INSERT INTO MEDICOS (CRM)
VALUES ('74766421');
INSERT INTO MEDICOS (CRM)
VALUES ('12458784');
INSERT INTO MEDICOS (CRM)
VALUES ('42090334');
INSERT INTO MEDICOS (CRM)
VALUES ('74718121');
INSERT INTO MEDICOS (CRM)
VALUES ('24147357');
INSERT INTO MEDICOS (CRM)
VALUES ('24224258');
INSERT INTO MEDICOS (CRM)
VALUES ('62776525');
INSERT INTO MEDICOS (CRM)
VALUES ('20375241');
INSERT INTO MEDICOS (CRM)
VALUES ('43503585');
INSERT INTO MEDICOS (CRM)
VALUES ('15237301');
INSERT INTO MEDICOS (CRM)
VALUES ('65612833');
INSERT INTO MEDICOS (CRM)
VALUES ('21618414');
INSERT INTO MEDICOS (CRM)
VALUES ('63336561');
INSERT INTO MEDICOS (CRM)
VALUES ('38346872');
INSERT INTO MEDICOS (CRM)
VALUES ('89598868');
INSERT INTO MEDICOS (CRM)
VALUES ('35263263');
INSERT INTO MEDICOS (CRM)
VALUES ('61842737');
INSERT INTO MEDICOS (CRM)
VALUES ('32265476');
INSERT INTO MEDICOS (CRM)
VALUES ('14135666');
INSERT INTO MEDICOS (CRM)
VALUES ('37571339');
INSERT INTO MEDICOS (CRM)
VALUES ('76711567');
INSERT INTO MEDICOS (CRM)
VALUES ('47822776');
INSERT INTO MEDICOS (CRM)
VALUES ('95614344');
INSERT INTO MEDICOS (CRM)
VALUES ('45858212');
INSERT INTO MEDICOS (CRM)
VALUES ('76760843');
INSERT INTO MEDICOS (CRM)
VALUES ('62648218');
INSERT INTO MEDICOS (CRM)
VALUES ('65168877');
INSERT INTO MEDICOS (CRM)
VALUES ('61978041');
INSERT INTO MEDICOS (CRM)
VALUES ('36364378');
INSERT INTO MEDICOS (CRM)
VALUES ('58694300');
INSERT INTO MEDICOS (CRM)
VALUES ('25507139');
INSERT INTO MEDICOS (CRM)
VALUES ('74738051');
INSERT INTO MEDICOS (CRM)
VALUES ('58062443');
INSERT INTO MEDICOS (CRM)
VALUES ('66238279');
INSERT INTO MEDICOS (CRM)
VALUES ('85548526');
INSERT INTO MEDICOS (CRM)
VALUES ('32777274');
INSERT INTO MEDICOS (CRM)
VALUES ('65839143');
INSERT INTO MEDICOS (CRM)
VALUES ('66425824');
INSERT INTO MEDICOS (CRM)
VALUES ('86592294');
INSERT INTO MEDICOS (CRM)
VALUES ('33256461');
INSERT INTO MEDICOS (CRM)
VALUES ('15376583');
INSERT INTO MEDICOS (CRM)
VALUES ('60046665');
INSERT INTO MEDICOS (CRM)
VALUES ('61818331');
INSERT INTO MEDICOS (CRM)
VALUES ('75750365');
INSERT INTO MEDICOS (CRM)
VALUES ('75754832');
INSERT INTO MEDICOS (CRM)
VALUES ('40357505');
INSERT INTO MEDICOS (CRM)
VALUES ('42410423');
INSERT INTO MEDICOS (CRM)
VALUES ('25987377');
INSERT INTO MEDICOS (CRM)
VALUES ('76787386');
INSERT INTO MEDICOS (CRM)
VALUES ('26252533');
INSERT INTO MEDICOS (CRM)
VALUES ('61295165');
INSERT INTO MEDICOS (CRM)
VALUES ('89203435');
INSERT INTO MEDICOS (CRM)
VALUES ('27182441');
INSERT INTO MEDICOS (CRM)
VALUES ('89711763');
INSERT INTO MEDICOS (CRM)
VALUES ('48353340');
INSERT INTO MEDICOS (CRM)
VALUES ('89869336');
INSERT INTO MEDICOS (CRM)
VALUES ('66465993');
INSERT INTO MEDICOS (CRM)
VALUES ('58659467');
INSERT INTO MEDICOS (CRM)
VALUES ('32701642');
INSERT INTO MEDICOS (CRM)
VALUES ('24349787');
INSERT INTO MEDICOS (CRM)
VALUES ('47618426');
INSERT INTO MEDICOS (CRM)
VALUES ('43446693');
INSERT INTO MEDICOS (CRM)
VALUES ('21632747');
INSERT INTO MEDICOS (CRM)
VALUES ('26967943');
INSERT INTO MEDICOS (CRM)
VALUES ('92652295');
INSERT INTO MEDICOS (CRM)
VALUES ('16601815');
INSERT INTO MEDICOS (CRM)
VALUES ('62768599');
INSERT INTO MEDICOS (CRM)
VALUES ('37245948');
INSERT INTO MEDICOS (CRM)
VALUES ('14356780');
INSERT INTO MEDICOS (CRM)
VALUES ('65693764');
INSERT INTO MEDICOS (CRM)
VALUES ('89277618');
INSERT INTO MEDICOS (CRM)
VALUES ('19115191');
INSERT INTO MEDICOS (CRM)
VALUES ('11283074');
INSERT INTO MEDICOS (CRM)
VALUES ('65033094');

-- -----------------------------------------------

INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4251.66');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1693.97');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4198.11');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3236.25');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1700.67');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3854.72');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4034.57');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3438.57');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$466.96');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2138.93');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2445.26');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3297.22');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3145.89');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3188.03');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$675.94');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2003.69');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2025.86');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2708.70');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2654.42');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4779.38');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3096.43');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3961.05');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3765.22');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2568.37');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2393.85');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2936.79');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3231.37');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4944.88');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3188.25');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4232.99');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3859.70');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4579.25');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2386.61');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3507.38');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1835.70');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2196.09');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1868.66');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4499.06');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2900.08');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1111.55');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2351.79');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2453.30');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$634.35');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1378.14');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3425.03');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$820.64');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4204.74');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4108.80');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2436.18');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4615.25');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2276.01');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$197.57');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4294.04');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2252.28');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$772.19');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$656.13');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2329.01');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4029.30');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3849.36');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1949.68');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2947.28');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3919.05');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4952.11');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1933.46');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3761.18');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4390.26');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$468.28');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$178.84');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4148.80');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4927.34');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1677.78');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3223.42');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3752.84');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4236.39');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4413.25');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$419.55');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3232.00');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1979.37');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1414.21');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4788.97');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2804.71');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1329.77');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$801.47');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2154.06');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1831.62');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2812.56');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$824.38');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4077.09');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2941.55');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2750.65');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2981.49');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4220.43');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3945.50');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2900.04');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1123.11');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3985.88');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$661.02');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2752.46');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$127.66');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4832.24');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1964.70');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1472.37');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4809.81');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3102.95');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$495.26');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2158.50');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2935.98');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4026.05');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4908.08');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3414.91');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3849.12');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3484.20');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1320.12');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4768.16');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1738.28');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2069.05');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$702.96');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3365.64');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3623.86');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$848.10');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2911.39');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2206.94');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3906.90');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2819.05');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$926.56');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4028.37');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3555.76');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$737.06');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2242.83');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3501.63');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4746.41');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3668.63');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3496.45');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$982.15');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4973.93');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3423.96');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3765.10');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3277.58');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$984.60');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2301.45');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1086.70');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$830.97');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2432.85');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$509.51');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3277.74');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$3430.33');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1740.17');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$4542.28');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$1352.23');
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ('$2748.57');

-- ------------------------------------

INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
