INSERT INTO MEDICOS ('05529373268', '05529373268', '05529373268')
INSERT INTO MEDICOS (CRM)
VALUES ('68643613');
INSERT INTO MEDICOS (CRM)
VALUES ('21884167');
INSERT INTO MEDICOS (CRM)
VALUES ('33522563');
INSERT INTO MEDICOS (CRM)
VALUES ('89242658');
INSERT INTO MEDICOS (CRM)
VALUES ('82091316');
INSERT INTO MEDICOS (CRM)
VALUES ('85789428');
INSERT INTO MEDICOS (CRM)
VALUES ('36792536');
INSERT INTO MEDICOS (CRM)
VALUES ('45833256');
INSERT INTO MEDICOS (CRM)
VALUES ('94115234');
INSERT INTO MEDICOS (CRM)
VALUES ('65883276');
INSERT INTO MEDICOS (CRM)
VALUES ('50578221');
INSERT INTO MEDICOS (CRM)
VALUES ('16061529');
INSERT INTO MEDICOS (CRM)
VALUES ('58231204');
INSERT INTO MEDICOS (CRM)
VALUES ('58929284');
INSERT INTO MEDICOS (CRM)
VALUES ('81688518');
INSERT INTO MEDICOS (CRM)
VALUES ('60681948');
INSERT INTO MEDICOS (CRM)
VALUES ('67256100');
INSERT INTO MEDICOS (CRM)
VALUES ('65508187');
INSERT INTO MEDICOS (CRM)
VALUES ('62269324');
INSERT INTO MEDICOS (CRM)
VALUES ('34411368');
INSERT INTO MEDICOS (CRM)
VALUES ('96867813');
INSERT INTO MEDICOS (CRM)
VALUES ('27551360');
INSERT INTO MEDICOS (CRM)
VALUES ('20013386');
INSERT INTO MEDICOS (CRM)
VALUES ('66043713');
INSERT INTO MEDICOS (CRM)
VALUES ('53078469');
INSERT INTO MEDICOS (CRM)
VALUES ('68007382');
INSERT INTO MEDICOS (CRM)
VALUES ('82127270');
INSERT INTO MEDICOS (CRM)
VALUES ('37123677');
INSERT INTO MEDICOS (CRM)
VALUES ('95454808');
INSERT INTO MEDICOS (CRM)
VALUES ('67554325');
INSERT INTO MEDICOS (CRM)
VALUES ('81577369');
INSERT INTO MEDICOS (CRM)
VALUES ('44315581');
INSERT INTO MEDICOS (CRM)
VALUES ('50306753');
INSERT INTO MEDICOS (CRM)
VALUES ('83112329');
INSERT INTO MEDICOS (CRM)
VALUES ('65040712');
INSERT INTO MEDICOS (CRM)
VALUES ('92410313');
INSERT INTO MEDICOS (CRM)
VALUES ('65437871');
INSERT INTO MEDICOS (CRM)
VALUES ('82785521');
INSERT INTO MEDICOS (CRM)
VALUES ('15681356');
INSERT INTO MEDICOS (CRM)
VALUES ('63278904');
INSERT INTO MEDICOS (CRM)
VALUES ('33354162');
INSERT INTO MEDICOS (CRM)
VALUES ('67554376');
INSERT INTO MEDICOS (CRM)
VALUES ('93585728');
INSERT INTO MEDICOS (CRM)
VALUES ('99214286');
INSERT INTO MEDICOS (CRM)
VALUES ('65187288');
INSERT INTO MEDICOS (CRM)
VALUES ('74766421');
INSERT INTO MEDICOS (CRM)
VALUES ('12458784');
INSERT INTO MEDICOS (CRM)
VALUES ('42090334');
INSERT INTO MEDICOS (CRM)
VALUES ('74718121');
INSERT INTO MEDICOS (CRM)
VALUES ('24147357');
INSERT INTO MEDICOS (CRM)
VALUES ('24224258');
INSERT INTO MEDICOS (CRM)
VALUES ('62776525');
INSERT INTO MEDICOS (CRM)
VALUES ('20375241');
INSERT INTO MEDICOS (CRM)
VALUES ('43503585');
INSERT INTO MEDICOS (CRM)
VALUES ('15237301');
INSERT INTO MEDICOS (CRM)
VALUES ('65612833');
INSERT INTO MEDICOS (CRM)
VALUES ('21618414');
INSERT INTO MEDICOS (CRM)
VALUES ('63336561');
INSERT INTO MEDICOS (CRM)
VALUES ('38346872');
INSERT INTO MEDICOS (CRM)
VALUES ('89598868');
INSERT INTO MEDICOS (CRM)
VALUES ('35263263');
INSERT INTO MEDICOS (CRM)
VALUES ('61842737');
INSERT INTO MEDICOS (CRM)
VALUES ('32265476');
INSERT INTO MEDICOS (CRM)
VALUES ('14135666');
INSERT INTO MEDICOS (CRM)
VALUES ('37571339');
INSERT INTO MEDICOS (CRM)
VALUES ('76711567');
INSERT INTO MEDICOS (CRM)
VALUES ('47822776');
INSERT INTO MEDICOS (CRM)
VALUES ('95614344');
INSERT INTO MEDICOS (CRM)
VALUES ('45858212');
INSERT INTO MEDICOS (CRM)
VALUES ('76760843');
INSERT INTO MEDICOS (CRM)
VALUES ('62648218');
INSERT INTO MEDICOS (CRM)
VALUES ('65168877');
INSERT INTO MEDICOS (CRM)
VALUES ('61978041');
INSERT INTO MEDICOS (CRM)
VALUES ('36364378');
INSERT INTO MEDICOS (CRM)
VALUES ('58694300');
INSERT INTO MEDICOS (CRM)
VALUES ('25507139');
INSERT INTO MEDICOS (CRM)
VALUES ('74738051');
INSERT INTO MEDICOS (CRM)
VALUES ('58062443');
INSERT INTO MEDICOS (CRM)
VALUES ('66238279');
INSERT INTO MEDICOS (CRM)
VALUES ('85548526');
INSERT INTO MEDICOS (CRM)
VALUES ('32777274');
INSERT INTO MEDICOS (CRM)
VALUES ('65839143');
INSERT INTO MEDICOS (CRM)
VALUES ('66425824');
INSERT INTO MEDICOS (CRM)
VALUES ('86592294');
INSERT INTO MEDICOS (CRM)
VALUES ('33256461');
INSERT INTO MEDICOS (CRM)
VALUES ('15376583');
INSERT INTO MEDICOS (CRM)
VALUES ('60046665');
INSERT INTO MEDICOS (CRM)
VALUES ('61818331');
INSERT INTO MEDICOS (CRM)
VALUES ('75750365');
INSERT INTO MEDICOS (CRM)
VALUES ('75754832');
INSERT INTO MEDICOS (CRM)
VALUES ('40357505');
INSERT INTO MEDICOS (CRM)
VALUES ('42410423');
INSERT INTO MEDICOS (CRM)
VALUES ('25987377');
INSERT INTO MEDICOS (CRM)
VALUES ('76787386');
INSERT INTO MEDICOS (CRM)
VALUES ('26252533');
INSERT INTO MEDICOS (CRM)
VALUES ('61295165');
INSERT INTO MEDICOS (CRM)
VALUES ('89203435');
INSERT INTO MEDICOS (CRM)
VALUES ('27182441');
INSERT INTO MEDICOS (CRM)
VALUES ('89711763');
INSERT INTO MEDICOS (CRM)
VALUES ('48353340');
INSERT INTO MEDICOS (CRM)
VALUES ('89869336');
INSERT INTO MEDICOS (CRM)
VALUES ('66465993');
INSERT INTO MEDICOS (CRM)
VALUES ('58659467');
INSERT INTO MEDICOS (CRM)
VALUES ('32701642');
INSERT INTO MEDICOS (CRM)
VALUES ('24349787');
INSERT INTO MEDICOS (CRM)
VALUES ('47618426');
INSERT INTO MEDICOS (CRM)
VALUES ('43446693');
INSERT INTO MEDICOS (CRM)
VALUES ('21632747');
INSERT INTO MEDICOS (CRM)
VALUES ('26967943');
INSERT INTO MEDICOS (CRM)
VALUES ('92652295');
INSERT INTO MEDICOS (CRM)
VALUES ('16601815');
INSERT INTO MEDICOS (CRM)
VALUES ('62768599');
INSERT INTO MEDICOS (CRM)
VALUES ('37245948');
INSERT INTO MEDICOS (CRM)
VALUES ('14356780');
INSERT INTO MEDICOS (CRM)
VALUES ('65693764');
INSERT INTO MEDICOS (CRM)
VALUES ('89277618');
INSERT INTO MEDICOS (CRM)
VALUES ('19115191');
INSERT INTO MEDICOS (CRM)
VALUES ('11283074');
INSERT INTO MEDICOS (CRM)
VALUES ('65033094');

-- -----------------------------------------------

INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4251);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1693);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4198);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3236);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1700);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3854);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4034);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3438);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (466);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2138);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2445);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3297);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3145);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3188);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (675);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2003);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2025);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2708);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2654);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4779);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3096);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3961);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3765);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2568);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2393);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2936);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3231);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4944);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3188);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4232);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3859);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4579);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2386);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3507);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1835);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2196);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1868);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4499);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2900);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1111);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2351);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2453);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (634);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1378);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3425);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (820);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4204);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4108);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2436);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4615);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2276);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (197);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4294);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2252);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (772);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (656);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2329);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4029);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3849);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1949);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2947);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3919);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4952);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1933);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3761);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4390);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (468);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (178);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4148);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4927);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1677);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3223);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3752);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4236);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4413);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (419);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3232);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1979);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1414);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4788);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2804);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1329);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (801);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2154);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1831);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2812);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (824);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4077);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2941);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2750);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2981);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4220);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3945);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2900);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1123);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3985);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (661);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2752);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (127);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4832);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1964);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1472);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4809);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3102);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (495);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2158);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2935);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4026);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4908);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3414);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3849);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3484);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1320);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4768);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1738);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2069);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (702);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3365);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3623);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (848);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2911);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2206);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3906);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2819);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (926);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4028);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3555);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (737);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2242);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3501);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4746);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3668);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3496);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (982);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4973);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3423);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3765);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3277);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (984);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2301);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1086);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (830);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2432);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (509);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3277);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (3430);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1740);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (4542);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (1352);
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES (2748);

-- ------------------------------------

INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('alimentacao');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('transporte');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('gfts');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('ferias');
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ('inss');
