-- Lembrar de criar script para insert de 30 recepcionistas!

INSERT INTO MEDICOS (CRM)
VALUES ("21916-181");
INSERT INTO MEDICOS (CRM)
VALUES ("68643-613");
INSERT INTO MEDICOS (CRM)
VALUES ("21884-167");
INSERT INTO MEDICOS (CRM)
VALUES ("33522563");
INSERT INTO MEDICOS (CRM)
VALUES ("89242-658");
INSERT INTO MEDICOS (CRM)
VALUES ("82091-316");
INSERT INTO MEDICOS (CRM)
VALUES ("85789-428");
INSERT INTO MEDICOS (CRM)
VALUES ("36792536");
INSERT INTO MEDICOS (CRM)
VALUES ("45833-256");
INSERT INTO MEDICOS (CRM)
VALUES ("94115-234");
INSERT INTO MEDICOS (CRM)
VALUES ("65883-276");
INSERT INTO MEDICOS (CRM)
VALUES ("50578-221");
INSERT INTO MEDICOS (CRM)
VALUES ("16061-529");
INSERT INTO MEDICOS (CRM)
VALUES ("58231-204");
INSERT INTO MEDICOS (CRM)
VALUES ("58929-284");
INSERT INTO MEDICOS (CRM)
VALUES ("81688-518");
INSERT INTO MEDICOS (CRM)
VALUES ("60681-948");
INSERT INTO MEDICOS (CRM)
VALUES ("67256-100");
INSERT INTO MEDICOS (CRM)
VALUES ("65508-187");
INSERT INTO MEDICOS (CRM)
VALUES ("62269-324");
INSERT INTO MEDICOS (CRM)
VALUES ("34411368");
INSERT INTO MEDICOS (CRM)
VALUES ("96867-813");
INSERT INTO MEDICOS (CRM)
VALUES ("27551-360");
INSERT INTO MEDICOS (CRM)
VALUES ("20013-386");
INSERT INTO MEDICOS (CRM)
VALUES ("66043-713");
INSERT INTO MEDICOS (CRM)
VALUES ("53078-469");
INSERT INTO MEDICOS (CRM)
VALUES ("68007-382");
INSERT INTO MEDICOS (CRM)
VALUES ("82127-270");
INSERT INTO MEDICOS (CRM)
VALUES ("37123677");
INSERT INTO MEDICOS (CRM)
VALUES ("95454-808");
INSERT INTO MEDICOS (CRM)
VALUES ("67554-325");
INSERT INTO MEDICOS (CRM)
VALUES ("81577-369");
INSERT INTO MEDICOS (CRM)
VALUES ("44315-581");
INSERT INTO MEDICOS (CRM)
VALUES ("50306-753");
INSERT INTO MEDICOS (CRM)
VALUES ("83112-329");
INSERT INTO MEDICOS (CRM)
VALUES ("65040-712");
INSERT INTO MEDICOS (CRM)
VALUES ("92410-313");
INSERT INTO MEDICOS (CRM)
VALUES ("65437-871");
INSERT INTO MEDICOS (CRM)
VALUES ("82785-521");
INSERT INTO MEDICOS (CRM)
VALUES ("15681-356");
INSERT INTO MEDICOS (CRM)
VALUES ("63278-904");
INSERT INTO MEDICOS (CRM)
VALUES ("33354162");
INSERT INTO MEDICOS (CRM)
VALUES ("67554-376");
INSERT INTO MEDICOS (CRM)
VALUES ("93585-728");
INSERT INTO MEDICOS (CRM)
VALUES ("99214-286");
INSERT INTO MEDICOS (CRM)
VALUES ("65187-288");
INSERT INTO MEDICOS (CRM)
VALUES ("74766-421");
INSERT INTO MEDICOS (CRM)
VALUES ("12458-784");
INSERT INTO MEDICOS (CRM)
VALUES ("42090-334");
INSERT INTO MEDICOS (CRM)
VALUES ("74718-121");
INSERT INTO MEDICOS (CRM)
VALUES ("24147-357");
INSERT INTO MEDICOS (CRM)
VALUES ("24224-258");
INSERT INTO MEDICOS (CRM)
VALUES ("62776-525");
INSERT INTO MEDICOS (CRM)
VALUES ("20375-241");
INSERT INTO MEDICOS (CRM)
VALUES ("43503-585");
INSERT INTO MEDICOS (CRM)
VALUES ("15237-301");
INSERT INTO MEDICOS (CRM)
VALUES ("65612-833");
INSERT INTO MEDICOS (CRM)
VALUES ("21618-414");
INSERT INTO MEDICOS (CRM)
VALUES ("63336-561");
INSERT INTO MEDICOS (CRM)
VALUES ("38346872");
INSERT INTO MEDICOS (CRM)
VALUES ("89598-868");
INSERT INTO MEDICOS (CRM)
VALUES ("35263263");
INSERT INTO MEDICOS (CRM)
VALUES ("61842-737");
INSERT INTO MEDICOS (CRM)
VALUES ("32265476");
INSERT INTO MEDICOS (CRM)
VALUES ("14135-666");
INSERT INTO MEDICOS (CRM)
VALUES ("37571339");
INSERT INTO MEDICOS (CRM)
VALUES ("76711-567");
INSERT INTO MEDICOS (CRM)
VALUES ("47822-776");
INSERT INTO MEDICOS (CRM)
VALUES ("95614-344");
INSERT INTO MEDICOS (CRM)
VALUES ("45858-212");
INSERT INTO MEDICOS (CRM)
VALUES ("76760-843");
INSERT INTO MEDICOS (CRM)
VALUES ("62648-218");
INSERT INTO MEDICOS (CRM)
VALUES ("65168-877");
INSERT INTO MEDICOS (CRM)
VALUES ("61978-041");
INSERT INTO MEDICOS (CRM)
VALUES ("36364378");
INSERT INTO MEDICOS (CRM)
VALUES ("58694-300");
INSERT INTO MEDICOS (CRM)
VALUES ("25507-139");
INSERT INTO MEDICOS (CRM)
VALUES ("74738-051");
INSERT INTO MEDICOS (CRM)
VALUES ("58062-443");
INSERT INTO MEDICOS (CRM)
VALUES ("66238-279");
INSERT INTO MEDICOS (CRM)
VALUES ("85548-526");
INSERT INTO MEDICOS (CRM)
VALUES ("32777274");
INSERT INTO MEDICOS (CRM)
VALUES ("65839-143");
INSERT INTO MEDICOS (CRM)
VALUES ("66425-824");
INSERT INTO MEDICOS (CRM)
VALUES ("86592-294");
INSERT INTO MEDICOS (CRM)
VALUES ("33256461");
INSERT INTO MEDICOS (CRM)
VALUES ("15376-583");
INSERT INTO MEDICOS (CRM)
VALUES ("60046-665");
INSERT INTO MEDICOS (CRM)
VALUES ("61818-331");
INSERT INTO MEDICOS (CRM)
VALUES ("75750-365");
INSERT INTO MEDICOS (CRM)
VALUES ("75754-832");
INSERT INTO MEDICOS (CRM)
VALUES ("40357-505");
INSERT INTO MEDICOS (CRM)
VALUES ("42410-423");
INSERT INTO MEDICOS (CRM)
VALUES ("25987-377");
INSERT INTO MEDICOS (CRM)
VALUES ("76787-386");
INSERT INTO MEDICOS (CRM)
VALUES ("26252-533");
INSERT INTO MEDICOS (CRM)
VALUES ("61295-165");
INSERT INTO MEDICOS (CRM)
VALUES ("89203-435");
INSERT INTO MEDICOS (CRM)
VALUES ("27182-441");
INSERT INTO MEDICOS (CRM)
VALUES ("89711-763");
INSERT INTO MEDICOS (CRM)
VALUES ("48353-340");
INSERT INTO MEDICOS (CRM)
VALUES ("89869-336");
INSERT INTO MEDICOS (CRM)
VALUES ("66465-993");
INSERT INTO MEDICOS (CRM)
VALUES ("58659-467");
INSERT INTO MEDICOS (CRM)
VALUES ("32701642");
INSERT INTO MEDICOS (CRM)
VALUES ("24349-787");
INSERT INTO MEDICOS (CRM)
VALUES ("47618-426");
INSERT INTO MEDICOS (CRM)
VALUES ("43446-693");
INSERT INTO MEDICOS (CRM)
VALUES ("21632-747");
INSERT INTO MEDICOS (CRM)
VALUES ("26967-943");
INSERT INTO MEDICOS (CRM)
VALUES ("92652-295");
INSERT INTO MEDICOS (CRM)
VALUES ("16601-815");
INSERT INTO MEDICOS (CRM)
VALUES ("62768-599");
INSERT INTO MEDICOS (CRM)
VALUES ("37245948");
INSERT INTO MEDICOS (CRM)
VALUES ("14356-780");
INSERT INTO MEDICOS (CRM)
VALUES ("65693-764");
INSERT INTO MEDICOS (CRM)
VALUES ("89277-618");
INSERT INTO MEDICOS (CRM)
VALUES ("19115-191");
INSERT INTO MEDICOS (CRM)
VALUES ("11283-074");
INSERT INTO MEDICOS (CRM)
VALUES ("65033-094");

-- -----------------------------------------------

INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4251.66");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1693.97");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4198.11");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3236.25");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1700.67");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3854.72");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4034.57");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3438.57");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$466.96");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2138.93");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2445.26");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3297.22");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3145.89");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3188.03");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$675.94");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2003.69");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2025.86");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2708.70");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2654.42");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4779.38");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3096.43");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3961.05");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3765.22");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2568.37");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2393.85");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2936.79");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3231.37");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4944.88");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3188.25");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4232.99");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3859.70");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4579.25");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2386.61");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3507.38");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1835.70");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2196.09");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1868.66");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4499.06");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2900.08");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1111.55");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2351.79");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2453.30");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$634.35");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1378.14");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3425.03");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$820.64");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4204.74");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4108.80");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2436.18");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4615.25");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2276.01");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$197.57");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4294.04");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2252.28");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$772.19");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$656.13");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2329.01");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4029.30");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3849.36");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1949.68");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2947.28");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3919.05");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4952.11");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1933.46");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3761.18");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4390.26");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$468.28");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$178.84");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4148.80");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4927.34");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1677.78");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3223.42");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3752.84");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4236.39");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4413.25");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$419.55");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3232.00");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1979.37");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1414.21");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4788.97");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2804.71");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1329.77");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$801.47");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2154.06");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1831.62");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2812.56");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$824.38");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4077.09");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2941.55");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2750.65");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2981.49");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4220.43");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3945.50");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2900.04");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1123.11");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3985.88");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$661.02");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2752.46");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$127.66");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4832.24");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1964.70");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1472.37");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4809.81");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3102.95");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$495.26");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2158.50");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2935.98");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4026.05");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4908.08");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3414.91");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3849.12");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3484.20");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1320.12");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4768.16");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1738.28");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2069.05");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$702.96");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3365.64");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3623.86");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$848.10");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2911.39");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2206.94");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3906.90");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2819.05");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$926.56");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4028.37");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3555.76");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$737.06");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2242.83");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3501.63");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4746.41");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3668.63");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3496.45");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$982.15");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4973.93");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3423.96");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3765.10");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3277.58");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$984.60");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2301.45");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1086.70");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$830.97");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2432.85");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$509.51");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3277.74");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$3430.33");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1740.17");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$4542.28");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$1352.23");
INSERT INTO PAGA_FUNCIONARIO (VALOR)
VALUES ("$2748.57");

-- -------------------------------------------------------------

INSERT INTO BENEFICIO (COD)
VALUES ("61742");
INSERT INTO BENEFICIO (COD)
VALUES ("24138");
INSERT INTO BENEFICIO (COD)
VALUES ("66035");
INSERT INTO BENEFICIO (COD)
VALUES ("26225");
INSERT INTO BENEFICIO (COD)
VALUES ("31136");
INSERT INTO BENEFICIO (COD)
VALUES ("81871");
INSERT INTO BENEFICIO (COD)
VALUES ("03723");
INSERT INTO BENEFICIO (COD)
VALUES ("26797");
INSERT INTO BENEFICIO (COD)
VALUES ("87411");
INSERT INTO BENEFICIO (COD)
VALUES ("07688");
INSERT INTO BENEFICIO (COD)
VALUES ("80118");
INSERT INTO BENEFICIO (COD)
VALUES ("25295");
INSERT INTO BENEFICIO (COD)
VALUES ("64671");
INSERT INTO BENEFICIO (COD)
VALUES ("46336");
INSERT INTO BENEFICIO (COD)
VALUES ("99641");
INSERT INTO BENEFICIO (COD)
VALUES ("11347");
INSERT INTO BENEFICIO (COD)
VALUES ("31920");
INSERT INTO BENEFICIO (COD)
VALUES ("60871");
INSERT INTO BENEFICIO (COD)
VALUES ("77853");
INSERT INTO BENEFICIO (COD)
VALUES ("58619");
INSERT INTO BENEFICIO (COD)
VALUES ("13085");
INSERT INTO BENEFICIO (COD)
VALUES ("85701");
INSERT INTO BENEFICIO (COD)
VALUES ("26470");
INSERT INTO BENEFICIO (COD)
VALUES ("55333");
INSERT INTO BENEFICIO (COD)
VALUES ("43088");
INSERT INTO BENEFICIO (COD)
VALUES ("86432");
INSERT INTO BENEFICIO (COD)
VALUES ("13373");
INSERT INTO BENEFICIO (COD)
VALUES ("99851");
INSERT INTO BENEFICIO (COD)
VALUES ("22381");
INSERT INTO BENEFICIO (COD)
VALUES ("51753");
INSERT INTO BENEFICIO (COD)
VALUES ("57751");
INSERT INTO BENEFICIO (COD)
VALUES ("75484");
INSERT INTO BENEFICIO (COD)
VALUES ("14119");
INSERT INTO BENEFICIO (COD)
VALUES ("43126");
INSERT INTO BENEFICIO (COD)
VALUES ("61535");
INSERT INTO BENEFICIO (COD)
VALUES ("68713");
INSERT INTO BENEFICIO (COD)
VALUES ("22464");
INSERT INTO BENEFICIO (COD)
VALUES ("36036");
INSERT INTO BENEFICIO (COD)
VALUES ("20772");
INSERT INTO BENEFICIO (COD)
VALUES ("98431");
INSERT INTO BENEFICIO (COD)
VALUES ("08468");
INSERT INTO BENEFICIO (COD)
VALUES ("66723");
INSERT INTO BENEFICIO (COD)
VALUES ("81235");
INSERT INTO BENEFICIO (COD)
VALUES ("13483");
INSERT INTO BENEFICIO (COD)
VALUES ("16708");
INSERT INTO BENEFICIO (COD)
VALUES ("22668");
INSERT INTO BENEFICIO (COD)
VALUES ("83773");
INSERT INTO BENEFICIO (COD)
VALUES ("07292");
INSERT INTO BENEFICIO (COD)
VALUES ("76076");
INSERT INTO BENEFICIO (COD)
VALUES ("96747");
INSERT INTO BENEFICIO (COD)
VALUES ("49781");
INSERT INTO BENEFICIO (COD)
VALUES ("34467");
INSERT INTO BENEFICIO (COD)
VALUES ("96096");
INSERT INTO BENEFICIO (COD)
VALUES ("66935");
INSERT INTO BENEFICIO (COD)
VALUES ("30897");
INSERT INTO BENEFICIO (COD)
VALUES ("38292");
INSERT INTO BENEFICIO (COD)
VALUES ("79498");
INSERT INTO BENEFICIO (COD)
VALUES ("23618");
INSERT INTO BENEFICIO (COD)
VALUES ("90651");
INSERT INTO BENEFICIO (COD)
VALUES ("15068");
INSERT INTO BENEFICIO (COD)
VALUES ("55517");
INSERT INTO BENEFICIO (COD)
VALUES ("12656");
INSERT INTO BENEFICIO (COD)
VALUES ("02076");
INSERT INTO BENEFICIO (COD)
VALUES ("15047");
INSERT INTO BENEFICIO (COD)
VALUES ("65436");
INSERT INTO BENEFICIO (COD)
VALUES ("51844");
INSERT INTO BENEFICIO (COD)
VALUES ("65652");
INSERT INTO BENEFICIO (COD)
VALUES ("67455");
INSERT INTO BENEFICIO (COD)
VALUES ("34724");
INSERT INTO BENEFICIO (COD)
VALUES ("65523");
INSERT INTO BENEFICIO (COD)
VALUES ("72544");
INSERT INTO BENEFICIO (COD)
VALUES ("12746");
INSERT INTO BENEFICIO (COD)
VALUES ("13444");
INSERT INTO BENEFICIO (COD)
VALUES ("33222");
INSERT INTO BENEFICIO (COD)
VALUES ("30140");
INSERT INTO BENEFICIO (COD)
VALUES ("12937");
INSERT INTO BENEFICIO (COD)
VALUES ("98325");
INSERT INTO BENEFICIO (COD)
VALUES ("23644");
INSERT INTO BENEFICIO (COD)
VALUES ("01157");
INSERT INTO BENEFICIO (COD)
VALUES ("70645");
INSERT INTO BENEFICIO (COD)
VALUES ("00190");
INSERT INTO BENEFICIO (COD)
VALUES ("83178");
INSERT INTO BENEFICIO (COD)
VALUES ("82734");
INSERT INTO BENEFICIO (COD)
VALUES ("59553");
INSERT INTO BENEFICIO (COD)
VALUES ("75748");
INSERT INTO BENEFICIO (COD)
VALUES ("31342");
INSERT INTO BENEFICIO (COD)
VALUES ("48841");
INSERT INTO BENEFICIO (COD)
VALUES ("07052");
INSERT INTO BENEFICIO (COD)
VALUES ("76163");
INSERT INTO BENEFICIO (COD)
VALUES ("18833");
INSERT INTO BENEFICIO (COD)
VALUES ("62467");
INSERT INTO BENEFICIO (COD)
VALUES ("83339");
INSERT INTO BENEFICIO (COD)
VALUES ("61643");
INSERT INTO BENEFICIO (COD)
VALUES ("39675");
INSERT INTO BENEFICIO (COD)
VALUES ("56178");
INSERT INTO BENEFICIO (COD)
VALUES ("41736");
INSERT INTO BENEFICIO (COD)
VALUES ("45341");
INSERT INTO BENEFICIO (COD)
VALUES ("21730");
INSERT INTO BENEFICIO (COD)
VALUES ("94698");
INSERT INTO BENEFICIO (COD)
VALUES ("25512");
INSERT INTO BENEFICIO (COD)
VALUES ("45850");
INSERT INTO BENEFICIO (COD)
VALUES ("96105");
INSERT INTO BENEFICIO (COD)
VALUES ("46925");
INSERT INTO BENEFICIO (COD)
VALUES ("07789");
INSERT INTO BENEFICIO (COD)
VALUES ("77195");
INSERT INTO BENEFICIO (COD)
VALUES ("37057");
INSERT INTO BENEFICIO (COD)
VALUES ("17103");
INSERT INTO BENEFICIO (COD)
VALUES ("78601");
INSERT INTO BENEFICIO (COD)
VALUES ("86778");
INSERT INTO BENEFICIO (COD)
VALUES ("54062");
INSERT INTO BENEFICIO (COD)
VALUES ("35284");
INSERT INTO BENEFICIO (COD)
VALUES ("96690");
INSERT INTO BENEFICIO (COD)
VALUES ("96146");
INSERT INTO BENEFICIO (COD)
VALUES ("14820");
INSERT INTO BENEFICIO (COD)
VALUES ("96759");
INSERT INTO BENEFICIO (COD)
VALUES ("40834");
INSERT INTO BENEFICIO (COD)
VALUES ("65009");
INSERT INTO BENEFICIO (COD)
VALUES ("65722");
INSERT INTO BENEFICIO (COD)
VALUES ("79293");
INSERT INTO BENEFICIO (COD)
VALUES ("24501");
INSERT INTO BENEFICIO (COD)
VALUES ("11261");
INSERT INTO BENEFICIO (COD)
VALUES ("51057");
INSERT INTO BENEFICIO (COD)
VALUES ("40334");
INSERT INTO BENEFICIO (COD)
VALUES ("37964");
INSERT INTO BENEFICIO (COD)
VALUES ("52494");
INSERT INTO BENEFICIO (COD)
VALUES ("75554");
INSERT INTO BENEFICIO (COD)
VALUES ("41337");
INSERT INTO BENEFICIO (COD)
VALUES ("68675");
INSERT INTO BENEFICIO (COD)
VALUES ("93072");
INSERT INTO BENEFICIO (COD)
VALUES ("92765");
INSERT INTO BENEFICIO (COD)
VALUES ("59629");
INSERT INTO BENEFICIO (COD)
VALUES ("15853");
INSERT INTO BENEFICIO (COD)
VALUES ("37325");
INSERT INTO BENEFICIO (COD)
VALUES ("66666");
INSERT INTO BENEFICIO (COD)
VALUES ("23445");
INSERT INTO BENEFICIO (COD)
VALUES ("40363");
INSERT INTO BENEFICIO (COD)
VALUES ("54863");
INSERT INTO BENEFICIO (COD)
VALUES ("76414");
INSERT INTO BENEFICIO (COD)
VALUES ("08435");
INSERT INTO BENEFICIO (COD)
VALUES ("73401");
INSERT INTO BENEFICIO (COD)
VALUES ("69686");
INSERT INTO BENEFICIO (COD)
VALUES ("55378");
INSERT INTO BENEFICIO (COD)
VALUES ("55781");
INSERT INTO BENEFICIO (COD)
VALUES ("81074");
INSERT INTO BENEFICIO (COD)
VALUES ("61957");
INSERT INTO BENEFICIO (COD)
VALUES ("74125");
INSERT INTO BENEFICIO (COD)
VALUES ("28515");
INSERT INTO BENEFICIO (COD)
VALUES ("71185");
INSERT INTO BENEFICIO (COD)
VALUES ("34232");
INSERT INTO BENEFICIO (COD)
VALUES ("42235");

-- ------------------------------------

INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("alimentacao");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("transporte");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("gfts");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("ferias");
INSERT INTO TIPO_BENEFICIO (TIPO)
VALUES ("inss");
