DROP TABLE AGENDAMENTO;

INSERT INTO AGENDAMENTO (COD)
VALUES ("93651");
INSERT INTO AGENDAMENTO (COD)
VALUES ("01055");
INSERT INTO AGENDAMENTO (COD)
VALUES ("69238");
INSERT INTO AGENDAMENTO (COD)
VALUES ("33425");
INSERT INTO AGENDAMENTO (COD)
VALUES ("38526");
INSERT INTO AGENDAMENTO (COD)
VALUES ("72709");
INSERT INTO AGENDAMENTO (COD)
VALUES ("76257");
INSERT INTO AGENDAMENTO (COD)
VALUES ("24442");
INSERT INTO AGENDAMENTO (COD)
VALUES ("18301");
INSERT INTO AGENDAMENTO (COD)
VALUES ("78538");
INSERT INTO AGENDAMENTO (COD)
VALUES ("65531");
INSERT INTO AGENDAMENTO (COD)
VALUES ("64463");
INSERT INTO AGENDAMENTO (COD)
VALUES ("35484");
INSERT INTO AGENDAMENTO (COD)
VALUES ("68686");
INSERT INTO AGENDAMENTO (COD)
VALUES ("41141");
INSERT INTO AGENDAMENTO (COD)
VALUES ("86886");
INSERT INTO AGENDAMENTO (COD)
VALUES ("29751");
INSERT INTO AGENDAMENTO (COD)
VALUES ("17855");
INSERT INTO AGENDAMENTO (COD)
VALUES ("34248");
INSERT INTO AGENDAMENTO (COD)
VALUES ("07768");
INSERT INTO AGENDAMENTO (COD)
VALUES ("33521");
INSERT INTO AGENDAMENTO (COD)
VALUES ("83869");
INSERT INTO AGENDAMENTO (COD)
VALUES ("89124");
INSERT INTO AGENDAMENTO (COD)
VALUES ("16961");
INSERT INTO AGENDAMENTO (COD)
VALUES ("75043");
INSERT INTO AGENDAMENTO (COD)
VALUES ("55933");
INSERT INTO AGENDAMENTO (COD)
VALUES ("43028");
INSERT INTO AGENDAMENTO (COD)
VALUES ("05133");
INSERT INTO AGENDAMENTO (COD)
VALUES ("68497");
INSERT INTO AGENDAMENTO (COD)
VALUES ("41184");
INSERT INTO AGENDAMENTO (COD)
VALUES ("42478");
INSERT INTO AGENDAMENTO (COD)
VALUES ("79129");
INSERT INTO AGENDAMENTO (COD)
VALUES ("41783");
INSERT INTO AGENDAMENTO (COD)
VALUES ("35494");
INSERT INTO AGENDAMENTO (COD)
VALUES ("78134");
INSERT INTO AGENDAMENTO (COD)
VALUES ("11128");
INSERT INTO AGENDAMENTO (COD)
VALUES ("48429");
INSERT INTO AGENDAMENTO (COD)
VALUES ("18878");
INSERT INTO AGENDAMENTO (COD)
VALUES ("24489");
INSERT INTO AGENDAMENTO (COD)
VALUES ("31459");
INSERT INTO AGENDAMENTO (COD)
VALUES ("85277");
INSERT INTO AGENDAMENTO (COD)
VALUES ("06729");
INSERT INTO AGENDAMENTO (COD)
VALUES ("84444");
INSERT INTO AGENDAMENTO (COD)
VALUES ("82386");
INSERT INTO AGENDAMENTO (COD)
VALUES ("68776");
INSERT INTO AGENDAMENTO (COD)
VALUES ("75805");
INSERT INTO AGENDAMENTO (COD)
VALUES ("21459");
INSERT INTO AGENDAMENTO (COD)
VALUES ("47676");
INSERT INTO AGENDAMENTO (COD)
VALUES ("15481");
INSERT INTO AGENDAMENTO (COD)
VALUES ("52967");
INSERT INTO AGENDAMENTO (COD)
VALUES ("89694");
INSERT INTO AGENDAMENTO (COD)
VALUES ("51824");
INSERT INTO AGENDAMENTO (COD)
VALUES ("72267");
INSERT INTO AGENDAMENTO (COD)
VALUES ("73358");
INSERT INTO AGENDAMENTO (COD)
VALUES ("97415");
INSERT INTO AGENDAMENTO (COD)
VALUES ("72226");
INSERT INTO AGENDAMENTO (COD)
VALUES ("31662");
INSERT INTO AGENDAMENTO (COD)
VALUES ("45521");
INSERT INTO AGENDAMENTO (COD)
VALUES ("31512");
INSERT INTO AGENDAMENTO (COD)
VALUES ("78462");
INSERT INTO AGENDAMENTO (COD)
VALUES ("83843");
INSERT INTO AGENDAMENTO (COD)
VALUES ("32741");
INSERT INTO AGENDAMENTO (COD)
VALUES ("47727");
INSERT INTO AGENDAMENTO (COD)
VALUES ("39456");
INSERT INTO AGENDAMENTO (COD)
VALUES ("18927");
INSERT INTO AGENDAMENTO (COD)
VALUES ("14764");
INSERT INTO AGENDAMENTO (COD)
VALUES ("25921");
INSERT INTO AGENDAMENTO (COD)
VALUES ("23761");
INSERT INTO AGENDAMENTO (COD)
VALUES ("68223");
INSERT INTO AGENDAMENTO (COD)
VALUES ("32477");
INSERT INTO AGENDAMENTO (COD)
VALUES ("85129");
INSERT INTO AGENDAMENTO (COD)
VALUES ("22648");
INSERT INTO AGENDAMENTO (COD)
VALUES ("26030");
INSERT INTO AGENDAMENTO (COD)
VALUES ("52688");
INSERT INTO AGENDAMENTO (COD)
VALUES ("12218");
INSERT INTO AGENDAMENTO (COD)
VALUES ("43564");
INSERT INTO AGENDAMENTO (COD)
VALUES ("31168");
INSERT INTO AGENDAMENTO (COD)
VALUES ("36213");
INSERT INTO AGENDAMENTO (COD)
VALUES ("94761");
INSERT INTO AGENDAMENTO (COD)
VALUES ("35717");
INSERT INTO AGENDAMENTO (COD)
VALUES ("24539");
INSERT INTO AGENDAMENTO (COD)
VALUES ("33304");
INSERT INTO AGENDAMENTO (COD)
VALUES ("97188");
INSERT INTO AGENDAMENTO (COD)
VALUES ("12599");
INSERT INTO AGENDAMENTO (COD)
VALUES ("75477");
INSERT INTO AGENDAMENTO (COD)
VALUES ("24473");
INSERT INTO AGENDAMENTO (COD)
VALUES ("38414");
INSERT INTO AGENDAMENTO (COD)
VALUES ("94228");
INSERT INTO AGENDAMENTO (COD)
VALUES ("24785");
INSERT INTO AGENDAMENTO (COD)
VALUES ("22236");
INSERT INTO AGENDAMENTO (COD)
VALUES ("57567");
INSERT INTO AGENDAMENTO (COD)
VALUES ("87631");
INSERT INTO AGENDAMENTO (COD)
VALUES ("25650");
INSERT INTO AGENDAMENTO (COD)
VALUES ("25437");
INSERT INTO AGENDAMENTO (COD)
VALUES ("75375");
INSERT INTO AGENDAMENTO (COD)
VALUES ("06282");
INSERT INTO AGENDAMENTO (COD)
VALUES ("36519");
INSERT INTO AGENDAMENTO (COD)
VALUES ("73017");
INSERT INTO AGENDAMENTO (COD)
VALUES ("24233");
INSERT INTO AGENDAMENTO (COD)
VALUES ("74145");
INSERT INTO AGENDAMENTO (COD)
VALUES ("80934");
INSERT INTO AGENDAMENTO (COD)
VALUES ("25306");
INSERT INTO AGENDAMENTO (COD)
VALUES ("25175");
INSERT INTO AGENDAMENTO (COD)
VALUES ("28870");
INSERT INTO AGENDAMENTO (COD)
VALUES ("41822");
INSERT INTO AGENDAMENTO (COD)
VALUES ("25986");
INSERT INTO AGENDAMENTO (COD)
VALUES ("43637");
INSERT INTO AGENDAMENTO (COD)
VALUES ("07605");
INSERT INTO AGENDAMENTO (COD)
VALUES ("35335");
INSERT INTO AGENDAMENTO (COD)
VALUES ("74883");
INSERT INTO AGENDAMENTO (COD)
VALUES ("56500");
INSERT INTO AGENDAMENTO (COD)
VALUES ("54483");
INSERT INTO AGENDAMENTO (COD)
VALUES ("44038");
INSERT INTO AGENDAMENTO (COD)
VALUES ("65521");
INSERT INTO AGENDAMENTO (COD)
VALUES ("62593");
INSERT INTO AGENDAMENTO (COD)
VALUES ("10325");
INSERT INTO AGENDAMENTO (COD)
VALUES ("39232");
INSERT INTO AGENDAMENTO (COD)
VALUES ("35498");
INSERT INTO AGENDAMENTO (COD)
VALUES ("33372");
INSERT INTO AGENDAMENTO (COD)
VALUES ("32724");
INSERT INTO AGENDAMENTO (COD)
VALUES ("51604");
INSERT INTO AGENDAMENTO (COD)
VALUES ("84147");
INSERT INTO AGENDAMENTO (COD)
VALUES ("31887");
INSERT INTO AGENDAMENTO (COD)
VALUES ("26558");
INSERT INTO AGENDAMENTO (COD)
VALUES ("87472");
INSERT INTO AGENDAMENTO (COD)
VALUES ("44056");
INSERT INTO AGENDAMENTO (COD)
VALUES ("42392");
INSERT INTO AGENDAMENTO (COD)
VALUES ("18795");
INSERT INTO AGENDAMENTO (COD)
VALUES ("20568");
INSERT INTO AGENDAMENTO (COD)
VALUES ("36775");
INSERT INTO AGENDAMENTO (COD)
VALUES ("51587");
INSERT INTO AGENDAMENTO (COD)
VALUES ("61357");
INSERT INTO AGENDAMENTO (COD)
VALUES ("75262");
INSERT INTO AGENDAMENTO (COD)
VALUES ("26871");
INSERT INTO AGENDAMENTO (COD)
VALUES ("21061");
INSERT INTO AGENDAMENTO (COD)
VALUES ("24271");
INSERT INTO AGENDAMENTO (COD)
VALUES ("88657");
INSERT INTO AGENDAMENTO (COD)
VALUES ("31598");
INSERT INTO AGENDAMENTO (COD)
VALUES ("40544");
INSERT INTO AGENDAMENTO (COD)
VALUES ("87158");
INSERT INTO AGENDAMENTO (COD)
VALUES ("18210");
INSERT INTO AGENDAMENTO (COD)
VALUES ("06168");
INSERT INTO AGENDAMENTO (COD)
VALUES ("19448");
INSERT INTO AGENDAMENTO (COD)
VALUES ("41546");
INSERT INTO AGENDAMENTO (COD)
VALUES ("34416");
INSERT INTO AGENDAMENTO (COD)
VALUES ("56279");
INSERT INTO AGENDAMENTO (COD)
VALUES ("63257");
INSERT INTO AGENDAMENTO (COD)
VALUES ("48038");
INSERT INTO AGENDAMENTO (COD)
VALUES ("26848");
INSERT INTO AGENDAMENTO (COD)
VALUES ("89465");
INSERT INTO AGENDAMENTO (COD)
VALUES ("63371");
INSERT INTO AGENDAMENTO (COD)
VALUES ("86936");
INSERT INTO AGENDAMENTO (COD)
VALUES ("78618");
INSERT INTO AGENDAMENTO (COD)
VALUES ("94196");
INSERT INTO AGENDAMENTO (COD)
VALUES ("73240");
INSERT INTO AGENDAMENTO (COD)
VALUES ("35167");
INSERT INTO AGENDAMENTO (COD)
VALUES ("76725");
INSERT INTO AGENDAMENTO (COD)
VALUES ("19278");
INSERT INTO AGENDAMENTO (COD)
VALUES ("45640");
INSERT INTO AGENDAMENTO (COD)
VALUES ("87686");
INSERT INTO AGENDAMENTO (COD)
VALUES ("84035");
INSERT INTO AGENDAMENTO (COD)
VALUES ("76928");
INSERT INTO AGENDAMENTO (COD)
VALUES ("73084");
INSERT INTO AGENDAMENTO (COD)
VALUES ("55857");
INSERT INTO AGENDAMENTO (COD)
VALUES ("89467");
INSERT INTO AGENDAMENTO (COD)
VALUES ("09715");
INSERT INTO AGENDAMENTO (COD)
VALUES ("53594");
INSERT INTO AGENDAMENTO (COD)
VALUES ("37773");
INSERT INTO AGENDAMENTO (COD)
VALUES ("86717");
INSERT INTO AGENDAMENTO (COD)
VALUES ("56118");
INSERT INTO AGENDAMENTO (COD)
VALUES ("47343");
INSERT INTO AGENDAMENTO (COD)
VALUES ("01230");
INSERT INTO AGENDAMENTO (COD)
VALUES ("23233");
INSERT INTO AGENDAMENTO (COD)
VALUES ("52843");
INSERT INTO AGENDAMENTO (COD)
VALUES ("04731");
INSERT INTO AGENDAMENTO (COD)
VALUES ("50781");
INSERT INTO AGENDAMENTO (COD)
VALUES ("11884");
INSERT INTO AGENDAMENTO (COD)
VALUES ("66763");
INSERT INTO AGENDAMENTO (COD)
VALUES ("92979");
INSERT INTO AGENDAMENTO (COD)
VALUES ("45422");
INSERT INTO AGENDAMENTO (COD)
VALUES ("17846");
INSERT INTO AGENDAMENTO (COD)
VALUES ("56532");
INSERT INTO AGENDAMENTO (COD)
VALUES ("71564");
INSERT INTO AGENDAMENTO (COD)
VALUES ("52897");
INSERT INTO AGENDAMENTO (COD)
VALUES ("01156");
INSERT INTO AGENDAMENTO (COD)
VALUES ("33480");
INSERT INTO AGENDAMENTO (COD)
VALUES ("57507");
INSERT INTO AGENDAMENTO (COD)
VALUES ("12803");
INSERT INTO AGENDAMENTO (COD)
VALUES ("18405");
INSERT INTO AGENDAMENTO (COD)
VALUES ("61028");
INSERT INTO AGENDAMENTO (COD)
VALUES ("77683");
INSERT INTO AGENDAMENTO (COD)
VALUES ("23272");
INSERT INTO AGENDAMENTO (COD)
VALUES ("88695");
INSERT INTO AGENDAMENTO (COD)
VALUES ("60896");
INSERT INTO AGENDAMENTO (COD)
VALUES ("54553");
INSERT INTO AGENDAMENTO (COD)
VALUES ("38747");
INSERT INTO AGENDAMENTO (COD)
VALUES ("62674");
INSERT INTO AGENDAMENTO (COD)
VALUES ("47329");
INSERT INTO AGENDAMENTO (COD)
VALUES ("26542");
INSERT INTO AGENDAMENTO (COD)
VALUES ("47899");

-- ------------------------------------------

DROP TABLE FORMULARIO;

INSERT INTO FORMULARIO (TIPO)
VALUES ("purus ac tellus. Suspendisse");
INSERT INTO FORMULARIO (TIPO)
VALUES ("nec tellus.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("vel sapien imperdiet");
INSERT INTO FORMULARIO (TIPO)
VALUES ("in, cursus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("ante ipsum primis in");
INSERT INTO FORMULARIO (TIPO)
VALUES ("In scelerisque scelerisque dui.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Donec");
INSERT INTO FORMULARIO (TIPO)
VALUES ("consectetuer rhoncus. Nullam");
INSERT INTO FORMULARIO (TIPO)
VALUES ("nulla magna, malesuada vel,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Cras eu tellus eu");
INSERT INTO FORMULARIO (TIPO)
VALUES ("id");
INSERT INTO FORMULARIO (TIPO)
VALUES ("lectus sit amet");
INSERT INTO FORMULARIO (TIPO)
VALUES ("fringilla est.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Maecenas mi");
INSERT INTO FORMULARIO (TIPO)
VALUES ("quis massa. Mauris vestibulum, neque");
INSERT INTO FORMULARIO (TIPO)
VALUES ("malesuada");
INSERT INTO FORMULARIO (TIPO)
VALUES ("pharetra. Quisque ac");
INSERT INTO FORMULARIO (TIPO)
VALUES ("orci quis");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Nunc ut");
INSERT INTO FORMULARIO (TIPO)
VALUES ("parturient");
INSERT INTO FORMULARIO (TIPO)
VALUES ("vitae, erat. Vivamus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Proin velit. Sed malesuada");
INSERT INTO FORMULARIO (TIPO)
VALUES ("leo.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("et libero.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("nisl arcu");
INSERT INTO FORMULARIO (TIPO)
VALUES ("blandit enim consequat purus. Maecenas");
INSERT INTO FORMULARIO (TIPO)
VALUES ("mus. Donec");
INSERT INTO FORMULARIO (TIPO)
VALUES ("tempus mauris");
INSERT INTO FORMULARIO (TIPO)
VALUES ("dapibus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("arcu eu");
INSERT INTO FORMULARIO (TIPO)
VALUES ("non, egestas a, dui.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Class aptent taciti sociosqu");
INSERT INTO FORMULARIO (TIPO)
VALUES ("semper et, lacinia vitae,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("at");
INSERT INTO FORMULARIO (TIPO)
VALUES ("non, lacinia at,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("magna tellus faucibus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("nulla. In tincidunt");
INSERT INTO FORMULARIO (TIPO)
VALUES ("fames ac");
INSERT INTO FORMULARIO (TIPO)
VALUES ("magnis dis parturient");
INSERT INTO FORMULARIO (TIPO)
VALUES ("tellus. Suspendisse");
INSERT INTO FORMULARIO (TIPO)
VALUES ("sed sem egestas");
INSERT INTO FORMULARIO (TIPO)
VALUES ("sapien imperdiet");
INSERT INTO FORMULARIO (TIPO)
VALUES ("convallis");
INSERT INTO FORMULARIO (TIPO)
VALUES ("fringilla est.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("placerat. Cras dictum");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Suspendisse");
INSERT INTO FORMULARIO (TIPO)
VALUES ("lacinia. Sed congue,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("turpis. Nulla aliquet. Proin velit.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("adipiscing fringilla, porttitor vulputate, posuere");
INSERT INTO FORMULARIO (TIPO)
VALUES ("condimentum. Donec at");
INSERT INTO FORMULARIO (TIPO)
VALUES ("nec, malesuada");
INSERT INTO FORMULARIO (TIPO)
VALUES ("magna. Ut tincidunt orci");
INSERT INTO FORMULARIO (TIPO)
VALUES ("sociis natoque penatibus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("turpis. In");
INSERT INTO FORMULARIO (TIPO)
VALUES ("eu,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("elit, dictum");
INSERT INTO FORMULARIO (TIPO)
VALUES ("fermentum vel, mauris. Integer");
INSERT INTO FORMULARIO (TIPO)
VALUES ("massa lobortis ultrices.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("eu, ultrices sit amet,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("nec, euismod in, dolor. Fusce");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Nullam");
INSERT INTO FORMULARIO (TIPO)
VALUES ("aliquam");
INSERT INTO FORMULARIO (TIPO)
VALUES ("vulputate, posuere vulputate,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("a odio semper cursus.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("est. Nunc ullamcorper, velit");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Curabitur egestas nunc sed libero.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("consectetuer, cursus et, magna.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("gravida nunc sed pede. Cum");
INSERT INTO FORMULARIO (TIPO)
VALUES ("tincidunt. Donec vitae");
INSERT INTO FORMULARIO (TIPO)
VALUES ("eu dui.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("risus odio, auctor vitae,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("tincidunt adipiscing. Mauris molestie");
INSERT INTO FORMULARIO (TIPO)
VALUES ("lectus. Nullam");
INSERT INTO FORMULARIO (TIPO)
VALUES ("erat, eget tincidunt dui augue");
INSERT INTO FORMULARIO (TIPO)
VALUES ("erat vitae");
INSERT INTO FORMULARIO (TIPO)
VALUES ("aliquet odio. Etiam ligula");
INSERT INTO FORMULARIO (TIPO)
VALUES ("venenatis vel, faucibus id, libero.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("metus eu erat semper rutrum.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("at, egestas a, scelerisque");
INSERT INTO FORMULARIO (TIPO)
VALUES ("ut quam");
INSERT INTO FORMULARIO (TIPO)
VALUES ("lacinia vitae, sodales");
INSERT INTO FORMULARIO (TIPO)
VALUES ("nunc risus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("lacus, varius et, euismod et,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("interdum feugiat. Sed nec");
INSERT INTO FORMULARIO (TIPO)
VALUES ("laoreet, libero et");
INSERT INTO FORMULARIO (TIPO)
VALUES ("velit dui, semper");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Vivamus nisi. Mauris nulla.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("erat. Vivamus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("congue a, aliquet");
INSERT INTO FORMULARIO (TIPO)
VALUES ("a feugiat tellus lorem");
INSERT INTO FORMULARIO (TIPO)
VALUES ("arcu vel quam");
INSERT INTO FORMULARIO (TIPO)
VALUES ("enim, gravida sit amet,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Curabitur consequat,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Suspendisse commodo tincidunt nibh.");
INSERT INTO FORMULARIO (TIPO)
VALUES ("pharetra. Nam ac");
INSERT INTO FORMULARIO (TIPO)
VALUES ("tellus,");
INSERT INTO FORMULARIO (TIPO)
VALUES ("Cras eget nisi");
INSERT INTO FORMULARIO (TIPO)
VALUES ("senectus et netus");
INSERT INTO FORMULARIO (TIPO)
VALUES ("iaculis, lacus pede sagittis");
INSERT INTO FORMULARIO (TIPO)
VALUES ("rutrum non,");
